### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by sudonims** [sudonims/vtop-da-deadline#8]
As I will be graduating soon and working on further things and I'll loose access to VTOP, it may become hard for me to keep working on the project. So, I'm looking for volunteers to keep maintaining the project. Comment here if you wish to be a maintainer

**Comment by sudonims** [comment]
@whoanuragverma, if you are interested you can let me know here...

**Comment by whoanuragverma** [comment]
Yeah sure, I'm interested.

**Comment by sudonims** [comment]
> Yeah sure, I'm interested.

Added you as collaborator...
